# Policy 04: Compliance Audit
# Everything flagged, nothing suppressed. Maximum visibility.
policy_name: compliance-audit
policy_version: "1.0"

pipeline:
  known_installer_domains: []
  benign_pipe_targets: []

credentials:
  known_test_values: []

file_limits:
  max_file_count: 25
  max_file_size_bytes: 1048576  # 1 MB
  max_reference_depth: 3
  max_name_length: 48
  max_description_length: 512
  min_description_length: 30

analysis_thresholds:
  zerowidth_threshold_with_decode: 10
  zerowidth_threshold_alone: 50
  analyzability_low_risk: 98
  analyzability_medium_risk: 90

sensitive_files:
  patterns:
    - '/etc/(?:passwd|shadow|hosts|sudoers|group)'
    - '~?/\.(?:ssh|aws|gnupg|config|env|kube|docker)'
    - '\.(?:env|pem|key|crt|p12|pfx|jks|keystore|secret)'
    - '(?:credentials|secrets?|tokens?|password|private|apikey)'
    - '\$(?:HOME|USER|SSH_AUTH_SOCK|AWS_|KUBECONFIG|DOCKER_)'

severity_overrides:
  - rule_id: BINARY_FILE_DETECTED
    severity: HIGH
    reason: "Audit requires all binaries flagged high"
  - rule_id: ARCHIVE_FILE_DETECTED
    severity: HIGH
    reason: "Audit requires all archives flagged high"
  - rule_id: HIDDEN_DATA_FILE
    severity: MEDIUM
    reason: "Audit requires all hidden files flagged"
  - rule_id: PYCACHE_FILES_DETECTED
    severity: HIGH
    reason: "Audit requires bytecode flagged high"
